import type { IconAliases, IconSet } from 'vuetify'
import FontAwesomeFreeIcon from './FontAwesomeFreeIcon.vue'

const aliases: IconAliases = {
  complete: 'fasl fa-check',
  cancel: 'fasl fa-xmark',
  close: 'fasl fa-xmark',
  delete: 'fasl fa-xmark',
  clear: 'fasl fa-xmark',
  success: 'fasl fa-circle-check',
  info: 'fass fa-circle-info',
  warning: 'fass fa-triangle-exclamation',
  error: 'fass fa-circle-exclamation',
  prev: 'fasl fa-chevron-left',
  next: 'fasl fa-chevron-right',
  checkboxOn: 'fasl fa-square-check',
  checkboxOff: 'fasl fa-square',
  checkboxIndeterminate: 'fasl fa-square-minus',
  delimiter: 'fasl fa-circle',
  sortAsc: 'fasl fa-sort-up',
  sortDesc: 'fasl fa-sort-down',
  expand: 'fasl fa-chevron-down',
  collapse: 'fasl fa-chevron-up',
  menu: 'fasl fa-bars',
  subgroup: 'fass fa-caret-down',
  dropdown: 'fass fa-caret-down',
  radioOn: 'fasl fa-circle-check',
  radioOff: 'fasl fa-circle',
  edit: 'fasl fa-pencil',
  ratingEmpty: 'fasl fa-star',
  ratingFull: 'fasl fa-star',
  ratingHalf: 'fasl fa-star-half',
  loading: 'fasl fa-spinner-third',
  first: 'fasl fa-angles-left',
  last: 'fasl fa-angles-right',
  unfold: 'fasl fa-caret-down',
  file: 'fasl fa-file',
  plus: 'fasl fa-plus',
  minus: 'fasl fa-minus',
  calendar: 'fasl fa-calendar',
  treeviewCollapse: 'fasl fa-angle-right',
  treeviewExpand: 'fasl fa-angle-down',
  eyeDropper: 'fasl fa-eye-dropper',
  upload: 'fasl fa-upload',
  color: 'fasl fa-palette',
  command: 'fasl fa-terminal',
  ctrl: 'fasl fa-keyboard',
  end: 'fasl fa-forward-step',
  escape: 'fasl fa-escape',
  home: 'fasl fa-house',
  insert: 'fasl fa-plus',
  space: 'fasl fa-expand',
  shift: 'fasl fa-arrow-long',
  alt: 'fasl fa-keyboard',
  enter: 'fasl fa-turn-down-left',
  tab: 'fasl fa-indent',
  backspace: 'fasl fa-delete-left',
  arrowup: 'fasl fa-angle-up',
  arrowdown: 'fasl fa-angle-down',
  arrowleft: 'fasl fa-angle-left',
  arrowright: 'fasl fa-angle-right',
}

const fa: IconSet = {
  component: FontAwesomeFreeIcon,
}

export { aliases, fa }
