export default {
  defaultTheme: 'light',
  themes: {
    light: {
      dark: false,
      colors: {
        primary: '#4D6BFE',
        'on-primary': '#FFFFFF',
        secondary: '#7B8798',
        'on-secondary': '#FFFFFF',
        info: '#3B82F6',
        'on-info': '#FFFFFF',
        success: '#158A52',
        'on-success': '#FFFFFF',
        warning: '#E9A23B',
        'on-warning': '#FFFFFF',
        error: '#D94B4B',
        'on-error': '#FFFFFF',
        background: '#F8FAFD',
        'on-background': '#162033',
        surface: '#FFFFFF',
        'on-surface': '#162033',
        'surface-variant': '#EEF3FB',
        'on-surface-variant': '#506078',
        feature: '#ed613f',
        'feature-secondary': '#ed9858',
        'on-feature': '#FFFFFF',
        'ai-tools': '#6B46C1',
        'on-ai-tools': '#FFFFFF',
        'accent-1': '#8fcf63',
        'on-accent-1': '#171717',
        'accent-2': '#41768b',
        'on-accent-2': '#FFFFFF',
        'accent-3': '#51a586',
        'on-accent-3': '#171717',
      },
      variables: {
        'border-color': '#C9D5E5',
        'border-opacity': '0.56',
        'table-header-color': '#F8FBFE',
        'scrollbar-thumb': '#C5D1E1',
        'disabled-opacity': '0.48',
        'medium-emphasis-opacity': '0.68',
        'high-emphasis-opacity': '0.9',
        'chart-fill-opacity': '0.2',
        'shadow-key-umbra-opacity': 'rgba(19, 30, 53, 0.07)',
        'shadow-key-penumbra-opacity': 'rgba(19, 30, 53, 0.06)',
        'shadow-key-ambient-opacity': 'rgba(19, 30, 53, 0.05)',
      },
    },
    dark: {
      dark: true,
      colors: {
        primary: '#4080F2',
        'on-primary': '#FFFFFF',
        secondary: '#95989F',
        'on-secondary': '#FFFFFF',
        info: '#5A87D7',
        'on-info': '#FFFFFF',
        success: '#3AA56E',
        'on-success': '#FFFFFF',
        warning: '#E9A23B',
        'on-warning': '#FFFFFF',
        error: '#E06D6D',
        'on-error': '#FFFFFF',
        background: '#171717',
        'on-background': '#F3F6FB',
        surface: '#1F1F1F',
        'on-surface': '#F3F6FB',
        'surface-variant': '#2A2A2A',
        'on-surface-variant': '#D8DEE8',
        feature: '#ed613f',
        'feature-secondary': '#ed9858',
        'on-feature': '#FFFFFF',
        'ai-tools': '#6B46C1',
        'on-ai-tools': '#FFFFFF',
        'accent-1': '#8FCF64',
        'on-accent-1': '#171717',
        'accent-2': '#41768b',
        'on-accent-2': '#FFFFFF',
        'accent-3': '#51a586',
        'on-accent-3': '#171717',
      },
      variables: {
        'border-color': '#4C4C4C',
        'border-opacity': '0.32',
        'table-header-color': '#232323',
        'disabled-opacity': '0.48',
        'scrollbar-thumb': '#555555',
        'medium-emphasis-opacity': '0.72',
        'high-emphasis-opacity': '0.9',
        'chart-fill-opacity': '0.2',
        'shadow-key-umbra-opacity': 'rgba(0, 0, 0, 0.24)',
        'shadow-key-penumbra-opacity': 'rgba(0, 0, 0, 0.18)',
        'shadow-key-ambient-opacity': 'rgba(0, 0, 0, 0.14)',
      },
    },
  },
  customProperties: true,
}
